### ISSUE TITLE
How to use CrossLinked with latin names?

### ISSUE THREAD

**Issue by iec989** [m8sec/CrossLinked#20]
In Spain and Latin America people have 2 surnames, their father's and mother.  

For instance, Jose Perez Rodriguez, José would be the name, and then Perez the first surname, and Rodriguez the second surname.

For the email addresses, we generally use name.surname**1**@company.com (_jose.perez@company.com_). Right now, with the current logic, it is taking name.surname**2**@company.com (_jose.rodriguez@company.com_). I assume that CrossLInked considers the surname1 as the second part of the firstname.

Is there any command option to take the first 2 strings as the firstname+surname, ignoring the 3th string?

**Comment by iec989** [comment]
Pull requests created from [iec989/CrossLinked](https://github.com/iec989/CrossLinked)

**Comment by m8sec** [comment]
Hi @iec989,

Appreciate your patience on this. I am just QA'ing a fix for this issue and should be pushed shortly.

You will now have the option to choose the position of the first and last names in the naming format:
```
>>> python3 crosslinked.py -f '{0:first}.{-2:last}@example.com' Example

Jose Perez Rodriguez  =  jose.perez@example.com
```

**Comment by m8sec** [comment]
I think we can close this now, but let me know if theres any issues.

And thank you for submitting a PR 🙏
