### ISSUE TITLE
Setup from README does not work anymore "setup.py install is deprecated"

### ISSUE THREAD

**Issue by HanseSecure** [m8sec/CrossLinked#27]
Hey ho,

i just want to try out your tool, but the default setup doesnt work anymore. Maybe you can check this ;-)

Thanks in advance

**Comment by m8sec** [comment]
Hi @HanseSecure,

Appreciate the issue and I have noticed this across other projects as well. Try install using the commands below and I will updated the README now 😄 

```bash
git clone https://github.com/m8sec/CrossLinked
cd CrossLinked
pip3 install .
```

OR directly from PyPi with:

`pip3 install crosslinked`


Ref
* [https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html)
* [https://github.com/pypa/setuptools/issues/917](https://github.com/pypa/setuptools/issues/917)
