### ISSUE TITLE
Google Results Always Return 429

### ISSUE THREAD

**Issue by oliv10** [m8sec/CrossLinked#35]
The requests to make the google search always return a 429, and then it is forwarded to a captcha.

**Comment by m8sec** [comment]
Hi @oliv10,

429 typically indicates you are hitting search engine Captcha requests. Trying using proxies, adding larger timeouts, increase jitters, or waiting between attempts. Unfortunately, this is common when attempting to spider search sites without any sort of api key or authorized request.
